services:
  luckblox-launcher-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: luckblox-node-fast
    ports:
      - "3001:3001"
      - "3002:3002"
    volumes:
      - .:/app
      - /app/Webserver/http-db-bridge/node_modules
    restart: always
